name: WoT Use Case Template
description: Submit Use Case
title: "[UC]: "
labels: ["Use Case"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - chachamimm
body:
  - type: markdown
    attributes:
      value: This is a issue templnate that is described a use case. Please fill in the required information for each item.
  - type: input
    id: Submitter
    attributes:
      label: Submitter
      description: Please enter your name.
      # placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: motivation1
    attributes:
      label: "Motivation - What to be done?"
      description: "Please describe any problems or improvements you would like to make in your use case."
    validations:
      required: true
  - type: textarea
    id: motivation2
    attributes:
      label: "Motivation - Why WoT? (Stackholder's interest in using WoT)"
      description: "Please describe why you would like to use WoT in your use case."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Please describe your use case details."
    validations:
      required: true
  - type: textarea
    id: targetusers
    attributes:
      label: "Expectations for stakeholders and environments - Target Users"
      description: Please describe your target users for your use cases.
    validations:
      required: false
  - type: textarea
    id: expecteddevices
    attributes:
      label: "Expectations for stakeholders and environments - Expected Devices"
      description: Please describe your expected devices for your use cases.
    validations:
      required: false
  - type: textarea
    id: expecteddata
    attributes:
      label: "Expectations for stakeholders and environments - Expected Data"
      description: Please descrive your expected data for your use cases.
    validations:
      required: false
  - type: textarea
    id: potentialadopters
    attributes:
      label: "Expectations for stakeholders and environments - Potential Adopters"
      description: Please descrive your potential adopters for your use cases.
    validations:
      required: false
  - type: textarea
    id: potentialapplications
    attributes:
      label: "Expectations for stakeholders and environments - Potential Applications"
      description: Please descrive your potential applications for your use cases.
    validations:
      required: false
  - type: textarea
    id: expectedprotocol
    attributes:
      label: "Expectations for stakeholders and environments - Expected Protocol"
      description: Please descrive your expected protocol for your use cases.
    validations:
      required: false
  - type: textarea
    id: existing-similar-wot-use-case
    attributes:
      label: "Existing similar WoT use case already defined?"
      description: If there are similar to your use case in [the WoT Use Cases and Requirements note](https://w3c.github.io/wot-usecases/), please describe them.
    validations:
      required: false
