name: WoT Use Case Template
description: Use this issue template to suggest a new use case for WoT standards
labels: ["WoT Use Case"]
title: "[UC]: "
assignees:
  - chachamimm
  - ashimura
body:
  - type: markdown
    attributes:
      value: This is an issue template to describe a use case. Please fill in the required information for each item below.

  - type: markdown
    attributes:
      value: |
        ## Title
        ----
  - type: input
    id: title
    attributes:
      label: Title
      description: |
        Simple title describing the use case briefly.
    validations:
      required: true
  - type: input
    id: Submitter
    attributes:
      label: Submitter
      description: Please enter your name.
      # placeholder: ex. email@example.com
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Motivation
        ----
  - type: textarea
    id: what_to_be_done
    attributes:
      label: "What to be done?"
      description: |
        Please describe any problems or improvements you would like to make in your use case.
    validations:
      required: true
  - type: textarea
    id: why_wot
    attributes:
      label: Why WoT? (Stackholder's interest in using WoT)
      description: |
        Please describe why you would like to use WoT in your use case.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: |
        Please explain how the spec meets the [spec selection criteria](https://github.com/w3c/browser-specs/#spec-selection-criteria), e.g., with a pointer to an intent to implement or to a sister project issue. You may leave this field blank if that seems straightforward.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Section 2
        ----

  - type: textarea
    id: custom
    attributes:
      label: Additional properties
      description: |
        A JSON object with the spec properties that cannot be determined automatically, e.g., [`seriesComposition`](https://github.com/w3c/browser-specs/#seriescomposition). Please **ignore this field** unless you know what you're doing. We will check and set properties as needed afterwards.
      render: json
      value: "{}"
    validations:
      required: false

