name: WoT Use Case Template
description: Use this issue template to suggest a new use case for WoT standards
labels: ["WoT Use Case"]
title: "Add new use case: <title>"
body:
  - type: markdown
    attributes:
      value: This is an issue template to describe a use case. Please fill in the required information for each item below.

  - type: input
    id: Submitter
    attributes:
      label: Submitter
      description: Please enter your name.
      # placeholder: ex. email@example.com
    validations:
      required: true
