name: "WoT Use Case Template"
description: "Use this issue template to suggest a new use case for WoT standards"
labels: ["WoT Use Case"]
title: "[UC]: "
body:

  - type: textarea
    id: uc-title
    attributes:
      label: "UC Title"
      description: |
        Simple title describing the use case briefly.
    validations:
      required: true
